In [57]:
import numpy as np 

import pandas as pd
import matplotlib.pyplot as plt

In [58]:
def simu(n, N):
    H = []
    for j in range(N):  
        h = []
        for i in range(n):
            u1 = np.random.random()
            x = -np.log(u1)
            hi = np.exp(x**2)
            h.append(hi)
        
        suma = np.sum(h)  
        es = suma / n      
        H.append(es)
        lista = dict(Estimadores = H)
        Estimadores = pd.DataFrame(lista)
    media = np.mean(H)
    var = np.var(H)
    
    return media, var, Estimadores



        
#Creamos dataframe
#datos = dict(salario = salario, empleo = empleo_anio)
#actuarios = pd.DataFrame(datos)
#actuarios.head()

In [61]:

n = 1000   # Por ejemplo
N = 1000  # Por ejemplo
media, varianza, Estimadores = simu(n, N)
print("Media:", media)
print("Varianza:", varianza)

Media: 4.561927142109492e+96
Varianza: 2.0790368070665354e+196

In [75]:
#Con varianza corregida, antitetico

def simu(n, N):
    H = []
    for j in range(N):  
        h = []
        k = []
        for i in range(n):
            u1 = np.random.random()
            x = -np.log(u1)
            y = -np.log(1-u1)
            hi = np.exp(x**2)
            h2 = np.exp(y**2)
            h.append(hi)
            
            k.append(h2)
        
        suma = np.sum(h)  
        es = suma / (n)  
        suma2 = np.sum(k)  
        es2 = suma / (n)
        
        H.append(es)
        H.append(es2)
        lista = dict(Estimadores = H)
        Estimadores = pd.DataFrame(lista)
    media = np.mean(H)
    var = np.var(H)
    
    return media, var, Estimadores

In [77]:
n = 1000   # Por ejemplo
N = 1000  # Por ejemplo
media, varianza, Estimadores = simu(n, N)
print("Media:", media)
print("Varianza:", varianza)
Estimadores

Media: 3.890154664144849e+78
Varianza: 1.5118140539391538e+160

       Estimadores
0     2.063827e+12
1     2.063827e+12
2     3.360281e+18
3     3.360281e+18
4     2.693923e+33
...            ...
1995  5.201222e+18
1996  7.654868e+19
1997  7.654868e+19
1998  8.686204e+28
1999  8.686204e+28

[2000 rows x 1 columns]

In [79]:
#Con varianza corregida, antitetico

def simu(n, N):
    H = []
    for j in range(N):  
        u1 = np.random.random(n)
        x = -np.log(u1)
        y = -np.log(1-u1)
        hi = np.exp(x**2)
        h2 = np.exp(y**2)

        es1 = np.mean(hi)
        es2 = np.mean(h2)
        
        H.append(es1)
        H.append(es2)
        lista = dict(Estimadores = H)
        Estimadores = pd.DataFrame(lista)
    media = np.mean(H)
    var = np.var(H)
    
    return media, var, Estimadores

In [81]:
n = 1000   # Por ejemplo
N = 1000  # Por ejemplo
media, varianza, Estimadores = simu(n, N)
print("Media:", media)
print("Varianza:", varianza)
Estimadores

Media: 2.205787031106118e+109
Varianza: 9.726127321088405e+221

       Estimadores
0     6.080100e+16
1     1.232647e+12
2     3.385812e+13
3     1.452659e+18
4     4.693846e+39
...            ...
1995  5.230406e+20
1996  6.610482e+21
1997  6.330879e+15
1998  2.966768e+21
1999  2.658159e+10

[2000 rows x 1 columns]